spring:
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  main:
    banner-mode: OFF

logging:
  config: classpath:log4j2-dev.xml