spring:
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
        query-passing: true
        preferIpAddress: true
  redis:
    database: 0
    host: 9.134.74.125
    port: 16379
    password: pass@bk

logging:
  config: classpath:log4j2-dev.xml