spring:
  cloud:
    consul:
      discovery:
        tags: __BK_REPO_CONSUL_TAG__
  data:
    mongodb:
      uri: __BK_REPO_MONGODB_URI__
      transaction:
        enabled: false
  redis:
    host: __BK_REPO_REDIS_HOST__
    password: __BK_REPO_REDIS_ADMIN_PASSWORD__
    port: __BK_REPO_REDIS_PORT__

logging:
  config: classpath:logback-config.xml
  path: __BK_REPO_LOGS_DIR__

storage:
  type: filesystem
  filesystem:
    path: __BK_REPO_FILE_PATH__

security:
  auth:
    enabled: true
