spring:
  cloud:
    consul:
      discovery:
        tags: bkce
  data:
    mongodb:
      uri: mongodb://__BK_REPO_MONGODB_ADDR__/__BK_REPO_MONGODB_DB_NAME__?maxPoolSize=100
      transaction:
        enabled: false

ribbon:
  gray:
    enabled: true

logging:
  config: classpath:logback-config.xml
  path: __BK_REPO_LOG_PATH__

storage:
  type: filesystem
  filesystem:
    path: __BK_REPO_FILE_PATH__
  monitor:
    enabled: false
  fileSizeThreshold: 5MB


# deprecated: http auth
auth:
  enabled: true
  jwt:
    secretKey: bkrepo@secret

security:
  # deprecated: service auth
  enabled: false
  auth:
    enabled: true
    jwt:
      secretKey: bkrepo@secret
  service:
    enabled: false
    secretKey: bkrepo@secret
