kind: ConfigMap
apiVersion: v1
metadata:
  name: repo-docker
data:
  application.yml: |-
    {{- toYaml .Values.docker.config | nindent 4 }}
    docker:
      domain: docker.{{ .Values.gateway.host }}
      auth:
        url: http://docker.{{ .Values.gateway.host }}/v2/auth