apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-auth
  labels:
    app: repo-auth
    {{- include "bkrepo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: repo-auth
  template:
    metadata:
      labels:
        app: repo-auth
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bkrepo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: repo-auth
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/auth:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BK_REPO_JVM_OPTION
              value: {{ .Values.common.jvmOption }}
            - name: BK_REPO_PROFILE
              value: {{ .Values.common.springProfile }}
          ports:
            - name: http
              containerPort: 25902
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/livenessState
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readinessState
              port: http
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 20
            periodSeconds: 5
          resources:
            {{- toYaml .Values.auth.resources | nindent 12 }}
      {{- with .Values.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
