{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: repo-ingress
  labels:
    {{- include "bkrepo.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.gateway.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: repo-gateway
              servicePort: 80
    - host: docker.{{ .Values.gateway.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: repo-gateway
              servicePort: 80
    - host: helm.{{ .Values.gateway.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: repo-gateway
              servicePort: 80
{{- end }}