{{- if .Values.jobs.initMongodb -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: repo-init-mongodb
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: repo-init-mongodb
          image: "{{ .Values.image.repository }}/init:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ['/bin/sh','-c','/data/workspace/init-mongodb.sh']
          env:
            - name: BK_REPO_USERNAME
              value: {{ .Values.common.username }}
            - name: BK_REPO_PASSWORD
              value: {{ .Values.common.password }}
            - name: BK_REPO_MONGODB_URI
              value: {{ .Values.common.mongodb.uri }}
      restartPolicy: OnFailure
{{- end }}
