apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage
spec:
  storageClassName: pv-storage
  accessModes:
  {{if .Values.volume.nfs.enabled }}
    - ReadWriteMany
  {{else}}
    - ReadWriteOnce
  {{end}}
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
  selector:
    matchLabels:
      pv: pv-storage