apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env.BK_REPO_SERVICE_PREFIX }}gateway
  labels:
    tier: frontend
    app: {{ .Values.env.BK_REPO_SERVICE_PREFIX }}gateway
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.env.BK_REPO_SERVICE_PREFIX }}gateway
