{{- if and (eq .Values.ingress.tls true)  (ne .Values.ingress.tls "") }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: bkrepo-tls
data:
  tls.crt: {{ .Values.ingress.tls.crt | b64enc }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
{{- end }}
